AdminPanel/Controllers/NewsController.cs
using AdminPanel.Interfaces;
using AdminPanel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Razor.Compilation;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace AdminPanel.Controllers
{
    public class NewsController : Controller, ICRUDController
    {
        ApplicationContext _context;
        IWebHostEnvironment _environment;

        public NewsController(ApplicationContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index() => View(await _context.News.Include(x => x.MediaFiles).ToListAsync());

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Details(int id) => View(await _context.News.Include(x => x.MediaFiles).FirstOrDefaultAsync(x => x.Id == id));

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Update(int id) => View(await _context.News.FindAsync(id));

        [HttpPost]
        public async Task<IActionResult> Update(int id, string name, string description)
        {
            var news = await _context.News.FindAsync(id);
            news.Name = name;
            news.Description = description;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var news = await _context.News.FindAsync(id);
            foreach(var mediaFile in news.MediaFiles)
            {
                System.IO.File.Delete(_environment.WebRootPath + mediaFile.Path);
            }
            _context.MediaFiles.RemoveRange(news.MediaFiles);
            _context.News.Remove(news);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name, string description, FormFileCollection uploadedFiles, string dateOfPublication)
        {
            var news = new News() { Name = name, Description = description, DateOfPublication = dateOfPublication };
            await _context.News.AddAsync(news);
            await _context.SaveChangesAsync();
            if (uploadedFiles != null)
            {
                foreach(var uploadedFile in uploadedFiles)
                {
                    var path = "/Media/" + uploadedFile.FileName;
                    using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
                    {
                        await uploadedFile.CopyToAsync(fileStream);
                    }
                    var mediaFile = new MediaFile() { Path = path };
                    await _context.MediaFiles.AddAsync(mediaFile);
                    await _context.SaveChangesAsync();
                    news.MediaFiles.Add(mediaFile);
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> UpdateMedia(int id) => View(await _context.News.Include(x => x.MediaFiles).FirstOrDefaultAsync(x => x.Id == id));

        [HttpPost]
        public async Task<IActionResult> MakeMainMediaFile(int id, int mediaFileId)
        {
            var mediaFile = await _context.MediaFiles.FindAsync(mediaFileId);
            var news = await _context.News.FindAsync(id);
            news.MediaFiles.Remove(mediaFile);
            news.MediaFiles.Insert(0, mediaFile);
            await _context.SaveChangesAsync();
            return RedirectToAction("UpdateMedia", new {id = id});
        }

        [HttpPost]
        public async Task<IActionResult> DeleteMediaFile(int id, string mediaFileId)
        {
            var mediaFile = await _context.MediaFiles.FindAsync(mediaFileId);
            System.IO.File.Delete(_environment.WebRootPath + mediaFile.Path);
            _context.MediaFiles.Remove(mediaFile);
            await _context.SaveChangesAsync();
            return RedirectToAction("UpdateMedia", new {id = id});
        }

        [HttpPost]
        public async Task<IActionResult> AddMediaFiles(int id, FormFileCollection uploadedFiles)
        {
            var news = await _context.News.FindAsync(id);
            if (uploadedFiles!=null)
            {
                foreach(var uploadedFile in uploadedFiles)
                {
                    var path = "/Media/" + uploadedFile.FileName;
                    using(var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
                    {
                        await uploadedFile.CopyToAsync(fileStream);
                    }
                    var mediaFile = new MediaFile() { Path = path };
                    await _context.MediaFiles.AddAsync(mediaFile);
                    await _context.SaveChangesAsync();
                    news.MediaFiles.Add(mediaFile);
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction("UpdateMedia", new { id = id });
        }
    }
}

AdminPanel/Controllers/ProjectController.cs
using AdminPanel.Interfaces;
using AdminPanel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdminPanel.Controllers
{
    public class ProjectController : Controller, ICRUDController
    {
        ApplicationContext _context;
        IWebHostEnvironment _environment;

        public ProjectController(ApplicationContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Index() => View(await _context.Projects.Include(x => x.Preview).ToListAsync());

        [Authorize]
        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name, IFormFile preview)
        {
            var project = new Project() { Name = name };
            await _context.Projects.AddAsync(project);
            await _context.SaveChangesAsync();

            if (preview is not null)
            {
                var path = "/Media/" + preview.FileName;
                using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
                {
                    await preview.CopyToAsync(fileStream);
                }
                var mediaFile = new MediaFile() { Path = path };
                await _context.MediaFiles.AddAsync(mediaFile);
                await _context.SaveChangesAsync();
                project.Preview = mediaFile;
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var project = await _context.Projects.Include(x => x.Preview).FirstOrDefaultAsync(x => x.Id == id);
            System.IO.File.Delete(_environment.WebRootPath + project.Preview.Path);
            _context.MediaFiles.Remove(project.Preview);
            _context.Projects.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Update(int id) => View(await _context.Projects.Include(x => x.Preview).FirstOrDefaultAsync(x => x.Id == id));

        [HttpPost]
        public async Task<IActionResult> Update(int id, string name, IFormFile preview)
        {
            var project = await _context.Projects.Include(x => x.Preview).FirstOrDefaultAsync(x => x.Id == id);
            project.Name = name;
            await _context.SaveChangesAsync();

            if (preview is not null)
            {
                System.IO.File.Delete(_environment.WebRootPath + project.Preview);
                var path = "/Media/" + preview.FileName;
                using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
                {
                    await preview.CopyToAsync(fileStream);
                }
                project.Preview.Path = path;
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public Task<IActionResult> UpdateMedia(int id)
        {
            throw new NotImplementedException();
        }

        [Authorize]
        [HttpGet]
        public Task<IActionResult> Details(int id)
        {
            throw new NotImplementedException();
        }
    }
}

AdminPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminPanel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminPanel.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Account/Login.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Achievement/Create.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Account/Index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Account/Update.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Account/UpdateMedia.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AdminPanel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AdminIndex">Admin Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Index">Calendar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Achievement" asp-action="Index">Achievements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="Index">News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AdminPanel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>