AdminPanel/Models/Achievement.cs
using AdminPanel.Interfaces;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdminPanel.Models
{
    public class Achievement : IContent
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public List<MediaFile>? MediaFiles { get; set; }
        public string? DateOfPublication { get; set; }

        public Achievement()
        {
            MediaFiles = new List<MediaFile>();
        }
    }
}

AdminPanel/Controllers/AchievementController.cs
using AdminPanel.Interfaces;
using AdminPanel.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdminPanel.Controllers
{
    public class AchievementController : Controller, ICRUDController
    {
        ApplicationContext _context;
        IWebHostEnvironment _environment;

        public AchievementController(ApplicationContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        [Authorize]
        public async Task<IActionResult> Index() => View(await _context.Achievements.Include(x => x.MediaFiles).ToListAsync());

        [Authorize]
        public async Task<IActionResult> Details(int id) => View(await _context.Achievements.Include(x => x.MediaFiles).FirstOrDefaultAsync(x => x.Id == id));

        [Authorize]
        public async Task<IActionResult> Update(int id) => View(await _context.Achievements.FindAsync(id));

        [HttpPost]
        public async Task<IActionResult> Update(int id, string name, string description)
        {
            var achievement = await _context.Achievements.FindAsync(id);
            achievement.Name = name;
            achievement.Description = description;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var achievement = await _context.Achievements.Include(x => x.MediaFiles).FirstOrDefaultAsync(x => x.Id == id);
            foreach(var mediaFile in achievement.MediaFiles)
            {
                System.IO.File.Delete(_environment.WebRootPath + mediaFile.Path);
            }
            _context.MediaFiles.RemoveRange(achievement.MediaFiles);
            _context.Achievements.Remove(achievement);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name, string description, FormFileCollection uploadedFiles, string dateOfPublication)
        {
            var achievement = new Achievement() { Name = name, Description = description, DateOfPublication = dateOfPublication };
            await _context.Achievements.AddAsync(achievement);
            await _context.SaveChangesAsync();
            if (uploadedFiles != null)
            {
                foreach (var uploadedFile in uploadedFiles)
                {
                    var path = "/Media/" + uploadedFile.FileName;
                    using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
                    {
                        await uploadedFile.CopyToAsync(fileStream);
                    }
                    var mediaFile = new MediaFile() { Path = path };
                    await _context.MediaFiles.AddAsync(mediaFile);
                    await _context.SaveChangesAsync();
                    achievement.MediaFiles.Add(mediaFile);
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> UpdateMedia(int id) => View(await _context.Achievements.Include(x => x.MediaFiles).FirstOrDefaultAsync(x => x.Id == id));

        [HttpPost]
        public async Task<IActionResult> DeleteMediaFile(int id, int mediaFileId)
        {
            var mediaFile = await _context.MediaFiles.FindAsync(mediaFileId);
            System.IO.File.Delete(_environment.WebRootPath + mediaFile.Path);
            _context.MediaFiles.Remove(mediaFile);
            await _context.SaveChangesAsync();
            return RedirectToAction("UpdateMedia", new { id = id });
        }

        [HttpPost]
        public async Task<IActionResult> AddMediaFiles(int id, FormFileCollection uploadedFiles)
        {
            var achievement = await _context.Achievements.FindAsync(id);
            if (uploadedFiles != null)
            {
                foreach (var uploadedFile in uploadedFiles)
                {
                    var path = "/Media/" + uploadedFile.FileName;
                    using (var fileStream = new FileStream(_environment.WebRootPath + path, FileMode.Create))
                    {
                        await uploadedFile.CopyToAsync(fileStream);
                    }
                    var mediaFile = new MediaFile() { Path = path };
                    await _context.MediaFiles.AddAsync(mediaFile);
                    await _context.SaveChangesAsync();
                    achievement.MediaFiles.Add(mediaFile);
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction("UpdateMedia", new { id = id });
        }
    }
}

AdminPanel/Views/Achievement/Create.cshtml
@model DateTime
@{
    Layout = "_Layout";

}
<link href="@Url.Content("~/wwwroot/css/Achievement/Create.css")" />

<h2>Create achievement</h2>
<form method="post" asp-action="Create" asp-controller="Achievement" asp-route-dateOfPublication="@DateTime.Now.ToString()" enctype="multipart/form-data">
    <label>Achievement name:</label><br />
    <input class="input" name="name" type="text"/><br />

    <label class ="text__create">Achievement description:</label><br />
    <textarea class="input" name="description"  type="text"></textarea><br />

    <label class="text__create">Achievemnt pictures:</label><br />
    <input class="chose__button" type="file" multiple name="uploadedFiles" value="Choose pictures" /><br />

    <input class="create__button" type="submit" value="Create" />
</form>

<form asp-action="Index" asp-controller="Achievement">
    <input class="back__button" type="submit" value="Back" />
</form>

AdminPanel/Views/Achievement/Details.cshtml
@model Achievement

<h1>@Model.Name</h1>

<p>
    @foreach (var mediaFile in Model.MediaFiles)
    {
        @if(mediaFile.Path.EndsWith(".mp4"))
        {
            <video height="100px" controls>
                <source src="@mediaFile.Path" type="video/mp4">
                @mediaFile.Path
            </video>
        }
        else
        {
            <img height="100px" src="@mediaFile.Path" alt="@mediaFile.Path">
        }
    }
</p>

<p>@Model.Description</p>

<form asp-action="Index" asp-controller="Achievement" method="get">
    <input type="submit" value="Back" />
</form>

AdminPanel/Views/Achievement/Index.cshtml
@model List<Achievement>
@{
    Layout = "_Layout";

}
<link href="@Url.Content("~/css/Achievement/Index.css")" rel="stylesheet" />

<table class="table">
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Media</th>
        <th colspan="2" style="text-align:center;">Actions</th>
        <th>Date of publication</th>
    </tr>
    @foreach(var achievement in Model)
    {
        <tr>
            <td><a asp-action="Details" asp-controller="Achievement" asp-route-id="@achievement.Id">@achievement.Name</a></td>
            <td>@achievement.Description</td>
            <td>
                @if(achievement.MediaFiles.Count != 0)
                {
                    @if (achievement.MediaFiles.First().Path.EndsWith(".mp4"))
                    {
                        <video height="80px" controls>
                            <source src="@achievement.MediaFiles.First().Path" type="video/mp4">
                            @achievement.MediaFiles.First().Path
                        </video>
                    }
                    else
                    {
                        <img height="80px" src="@achievement.MediaFiles.First().Path" alt="@achievement.MediaFiles.First().Path">
                    }
                }
                <form method="get" asp-action="UpdateMedia" asp-controller="Achievement" asp-route-id="@achievement.Id">
                    <input class="update__button" type="submit" value="Update media files" />
                </form>
            </td>
            <td>
                <form method="get" asp-action="Update" asp-controller="Achievement" asp-route-id="@achievement.Id">
                    <input class="edita__button" type="submit" value="Edit" />
                </form>
            </td>
            <td>
                <form method="post" asp-action="Delete" asp-controller="Achievement" asp-route-id="@achievement.Id">
                    <input class="delete__button" type="submit" value="Delete" />
                </form>
            </td>
            <td>@achievement.DateOfPublication</td>
        </tr>
    }
</table>

<form method="get" asp-action="Create" asp-controller="Achievement">
    <input class="creates__button" type="submit" value="Create an achievement" />
</form>

AdminPanel/Views/Achievement/Update.cshtml
@model Achievement
@{
    Layout = "_Layout";

}
<link href="@Url.Content("~/wwwroot/css/Achievement/Update.css")" />

<h2>Edit the achievement</h2>
<form method="post" asp-action="Update" asp-controller="Achievement" asp-route-id="@Model.Id">
    <label>Achievement name: </label><br />
    <input class="input" name="name" type="text" value="@Model.Name"/><br />

    <label >Achievement description: </label><br />
    <textarea class="input" name="description" type="text">@Model.Description</textarea><br />

    <input class="input" type="submit" value="Save changes" />
</form>

<form method="get" asp-action="Index" asp-controller="Achievement">
    <input type="submit" value="Back" />
</form>

AdminPanel/Views/Achievement/UpdateMedia.cshtml
@model Achievement

@{
    var mediaFiles = Model.MediaFiles.ToList();
}
@{
    Layout = "_Layout";

}
<link href="@Url.Content("~/css/Achievement/UpdateMedia.css")" rel="stylesheet" />

<div class="media__files">
        @foreach(var mediaFile in mediaFiles)
        {
        <div class="media__file">
            @if(mediaFile.Path.EndsWith("mp4"))
            {
                <video height="100px" controls>
                    <source src="@mediaFile.Path" type="video/mp4">
                    @mediaFile.Path
                </video>
            }
            else
            {
                <img height="100px" src="@mediaFile.Path" alt="@mediaFile.Path" />
            }
            <form method="post" asp-action="DeleteMediaFile" asp-controller="Achievement" asp-route-id="@Model.Id" asp-route-mediaFileId="@mediaFile.Id">
                <input class="input" type="submit" value="Delete" />
            </form>
        </div>
        }
</div>

<form method="post" asp-action="AddMediaFiles" asp-controller="Achievement" asp-route-id="@Model.Id" enctype="multipart/form-data">
    <label class="pic">Add media files:</label><br />
    <input class="vibor__update" type="file" multiple name="uploadedFiles" /><br />
    <input class="add__update" type="submit" value="Add" />
</form>

<form method="get" asp-action="Index" asp-controller="Achievement">
    <input class="back__update" type="submit" value="Back" />
</form>